version: '3'

services:
  challenge-db:
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_DB=order_logs
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    expose:
      - 5432
    volumes:
      - ./psql_data:/var/lib/postgresql

  data-processor:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - challenge-db
