version: '3'

services:
  challenge-db:
    image: "postgres:13-alpine"
    # Change to use env file in real use cases
    environment: 
      - POSTGRES_DB=captec_challenge
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    expose:
      - 5432
    volumes:
      - ./psql_data:/var/lib/postgresql

  data-processor:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - challenge-db
