version: '3'

services:
  data-processor:
    container_name: data-prc
    build:
      context: .
      dockerfile: Dockerfile
    # links:
      # - "challenge-db:database"
    volumes:
      - .:/app/

  challenge-db:
    container_name: captec-db
    image: "postgres:13-alpine"
    # Change to use env file in real use cases
    environment: 
      - POSTGRES_DB=captec_challenge
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./psql_data:/var/lib/postgresql

