version: '3'

services:
  data-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-prc
    depends_on:
      challenge-db:
        condition: service_healthy
    volumes:
      - .:/app/

  challenge-db:
    container_name: captec-db
    image: "postgres:13-alpine"
    # Change to use env file in real use cases
    environment: 
      - POSTGRES_DB=captec_challenge
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ./psql_data:/var/lib/postgresql

